//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOfFund.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int donation_id { get; set; }
        public string donation_name { get; set; }
        public string donation_surname { get; set; }
        public Nullable<int> donation_sum { get; set; }
        public int date_id { get; set; }
        public int dfund_id { get; set; }
    
        public virtual MyDate MyDate { get; set; }
        public virtual Fund Fund { get; set; }
    }
}
