//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOfFund.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FundWorkEntities : DbContext
    {
        public FundWorkEntities()
            : base("name=FundWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Child> Child { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Clinic> Clinic { get; set; }
        public virtual DbSet<Diagnosis> Diagnosis { get; set; }
        public virtual DbSet<Donation> Donation { get; set; }
        public virtual DbSet<EventType> EventType { get; set; }
        public virtual DbSet<Fund> Fund { get; set; }
        public virtual DbSet<FundBudget> FundBudget { get; set; }
        public virtual DbSet<MyDate> MyDate { get; set; }
        public virtual DbSet<MyEvent> MyEvent { get; set; }
        public virtual DbSet<MyLocation> MyLocation { get; set; }
        public virtual DbSet<MyPriority> MyPriority { get; set; }
        public virtual DbSet<MyStatus> MyStatus { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
