//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOfFund.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundBudget
    {
        public int fundbudget_id { get; set; }
        public Nullable<int> fondbudget_sum { get; set; }
        public string fundbudget_baccount { get; set; }
        public int ffund_id { get; set; }
    
        public virtual Fund Fund { get; set; }
    }
}
