//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOfFund.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyEvent
    {
        public int event_id { get; set; }
        public string event_description { get; set; }
        public Nullable<int> event_sum { get; set; }
        public int elocation_id { get; set; }
        public int eeventtype_id { get; set; }
        public int edate_id { get; set; }
        public int efund_id { get; set; }
        public int estatus_id { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual Fund Fund { get; set; }
        public virtual MyDate MyDate { get; set; }
        public virtual MyLocation MyLocation { get; set; }
        public virtual MyStatus MyStatus { get; set; }
    }
}
