//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOfFund.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int worker_id { get; set; }
        public string worker_name { get; set; }
        public string worker_surname { get; set; }
        public string worker_login { get; set; }
        public string worker_password { get; set; }
        public int wfund_id { get; set; }
        public int wposition_id { get; set; }
    
        public virtual Fund Fund { get; set; }
        public virtual Position Position { get; set; }
    }
}
